//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baidu.AI.Ocr.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Baidu.AI.Ocr.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file path to the image for recognition..
        /// </summary>
        internal static string BaiduOcrActivityImagePathDescription {
            get {
                return ResourceManager.GetString("BaiduOcrActivityImagePathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImagePath.
        /// </summary>
        internal static string BaiduOcrActivityImagePathDisplayName {
            get {
                return ResourceManager.GetString("BaiduOcrActivityImagePathDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result of the recognition in the form of JSON..
        /// </summary>
        internal static string BaiduOcrActivityResultDescription {
            get {
                return ResourceManager.GetString("BaiduOcrActivityResultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string BaiduOcrActivityResultDisplayName {
            get {
                return ResourceManager.GetString("BaiduOcrActivityResultDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baidu OCR Scope.
        /// </summary>
        internal static string BaiduOcrScope {
            get {
                return ResourceManager.GetString("BaiduOcrScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains and authenticates all Baidu OCR activities..
        /// </summary>
        internal static string BaiduOcrScopeDescription {
            get {
                return ResourceManager.GetString("BaiduOcrScopeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the recognized values of a birth certificate..
        /// </summary>
        internal static string BirthCertificateActivityDescription {
            get {
                return ResourceManager.GetString("BirthCertificateActivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Certificate.
        /// </summary>
        internal static string BirthCertificateActivityDisplayName {
            get {
                return ResourceManager.GetString("BirthCertificateActivityDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the recognized values of a HK and Macau pass..
        /// </summary>
        internal static string HkMacauExitentrypermitActivityDescription {
            get {
                return ResourceManager.GetString("HkMacauExitentrypermitActivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HK and Macau Pass.
        /// </summary>
        internal static string HkMacauExitentrypermitActivityDisplayName {
            get {
                return ResourceManager.GetString("HkMacauExitentrypermitActivityDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the recognized values of a household register..
        /// </summary>
        internal static string HouseholdRegisterActivityDescription {
            get {
                return ResourceManager.GetString("HouseholdRegisterActivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Household Register.
        /// </summary>
        internal static string HouseholdRegisterActivityDisplayName {
            get {
                return ResourceManager.GetString("HouseholdRegisterActivityDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the recognized values of an ID Card. Front and back sides to be recognized separately..
        /// </summary>
        internal static string IdCardActivityDescription {
            get {
                return ResourceManager.GetString("IdCardActivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Card.
        /// </summary>
        internal static string IdCardActivityDisplayName {
            get {
                return ResourceManager.GetString("IdCardActivityDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID card side, front or back..
        /// </summary>
        internal static string IdCardSideDescription {
            get {
                return ResourceManager.GetString("IdCardSideDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdCardSide.
        /// </summary>
        internal static string IdCardSideDisplayName {
            get {
                return ResourceManager.GetString("IdCardSideDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value for {0}..
        /// </summary>
        internal static string MetadataValidationError {
            get {
                return ResourceManager.GetString("MetadataValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the recognized values of a passport..
        /// </summary>
        internal static string PassportActivityDescription {
            get {
                return ResourceManager.GetString("PassportActivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport.
        /// </summary>
        internal static string PassportActivityDisplayName {
            get {
                return ResourceManager.GetString("PassportActivityDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the recognized values of a quota invoice..
        /// </summary>
        internal static string QuotaInvoiceActivityDescription {
            get {
                return ResourceManager.GetString("QuotaInvoiceActivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quota Invoice.
        /// </summary>
        internal static string QuotaInvoiceActivityDisplayName {
            get {
                return ResourceManager.GetString("QuotaInvoiceActivityDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the recognized values of a Taiwan pass..
        /// </summary>
        internal static string TaiwanExitentrypermitActivityDescription {
            get {
                return ResourceManager.GetString("TaiwanExitentrypermitActivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taiwan Pass.
        /// </summary>
        internal static string TaiwanExitentrypermitActivityDisplayName {
            get {
                return ResourceManager.GetString("TaiwanExitentrypermitActivityDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxi Receipt.
        /// </summary>
        internal static string TaxiReceiptActivityDisplayName {
            get {
                return ResourceManager.GetString("TaxiReceiptActivityDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the recognized values of a taxi receipt..
        /// </summary>
        internal static string TaxiReceiptActivityescription {
            get {
                return ResourceManager.GetString("TaxiReceiptActivityescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the recognized values of a train ticket..
        /// </summary>
        internal static string TrainTicketActivityDescription {
            get {
                return ResourceManager.GetString("TrainTicketActivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train Ticket.
        /// </summary>
        internal static string TrainTicketActivityDisplayName {
            get {
                return ResourceManager.GetString("TrainTicketActivityDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity is only valid inside a Baidu OCR Scope..
        /// </summary>
        internal static string ValidationMessage {
            get {
                return ResourceManager.GetString("ValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the recognized values of a VAT invoice..
        /// </summary>
        internal static string VatInvoiceActivityDescription {
            get {
                return ResourceManager.GetString("VatInvoiceActivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT Invoice.
        /// </summary>
        internal static string VatInvoiceActivityDisplayName {
            get {
                return ResourceManager.GetString("VatInvoiceActivityDisplayName", resourceCulture);
            }
        }
    }
}
